# Generated by pybot-sdk. Edit config/hardware.yml instead.

SCHEMA_VERSION = 1

ROBOT = {'name': 'example_bot'}

CAN_BUSES = {'rio': {'name': 'rio', 'vendor_bus_name': ''}}

CONTROLLERS = {'driver': {'name': 'driver', 'port': 0, 'type': 'xbox'}}

DEVICES = {'drive_left': {'bus': 'rio',
                'can_id': 1,
                'inverted': False,
                'motor': 'kraken',
                'name': 'drive_left',
                'subsystem': 'drivetrain',
                'type': 'talon_fx'},
 'drive_right': {'bus': 'rio',
                 'can_id': 4,
                 'inverted': True,
                 'motor': 'kraken',
                 'name': 'drive_right',
                 'subsystem': 'drivetrain',
                 'type': 'talon_fx'}}

MAGICBOT = {'components': [{'devices': ['drive_left', 'drive_right'], 'name': 'drivetrain'}]}
