"""Deterministic Python-data generation from validated hardware maps."""

import ast
import os
from pathlib import Path
import pprint
import tempfile
from typing import Any


def render_hardware_module(document: dict[str, Any]) -> str:
    constants = (
        ("ROBOT", "robot"),
        ("CAN_BUSES", "can_buses"),
        ("CONTROLLERS", "controllers"),
        ("DEVICES", "devices"),
        ("MAGICBOT", "magicbot"),
    )
    lines = [
        "# Generated by pybot-sdk. Edit config/hardware.yml instead.",
        f"SCHEMA_VERSION = {document['schema_version']}",
    ]
    for constant, key in constants:
        if key == "controllers" or key == "devices":
            value = {entry["name"]: entry for entry in document[key]}
        elif key == "can_buses":
            value = {entry["name"]: entry for entry in document[key]}
        else:
            value = document[key]
        lines.append(f"{constant} = {pprint.pformat(value, sort_dicts=True, width=88)}")
    output = "\n\n".join(lines) + "\n"
    ast.parse(output)
    return output


def write_hardware_module(
    content: str,
    source_path: Path,
    output_path: Path,
    *,
    force: bool = False,
) -> bool:
    source_path = source_path.expanduser().resolve()
    output_path = output_path.expanduser()
    if output_path.is_symlink():
        raise FileExistsError(f"refusing to write through symlink: {output_path}")
    if output_path.resolve() == source_path:
        raise ValueError("generated output must not replace its YAML source")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not force:
        if output_path.is_file() and output_path.read_text(encoding="utf-8") == content:
            return False
        raise FileExistsError(
            f"refusing to overwrite {output_path}; pass --force to replace it"
        )

    if not force:
        with output_path.open("x", encoding="utf-8", newline="\n") as output_file:
            output_file.write(content)
        return True

    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=output_path.parent,
            delete=False,
        ) as output_file:
            temporary_path = Path(output_file.name)
            output_file.write(content)
        os.replace(temporary_path, output_path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
    return True